# Generated by Django 4.0.4 on 2022-04-23 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, db_column='update_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
