# Generated by Django 4.0.4 on 2022-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='passwd',
            field=models.CharField(db_column='passwd', max_length=255),
        ),
    ]
