# Generated by Django 4.0.4 on 2022-05-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image1',
            field=models.ImageField(blank=True, db_column='image1', max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='upfile1',
            field=models.FileField(blank=True, db_column='upfile1', max_length=255, upload_to=''),
        ),
    ]
